In [1]:
import utility as util
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df=util.load_csv_to_df("labelled_ycombi.csv")

/home/shayoni/mainak/DeveloperReactionToAPIChanges/Mainak/utility.py:3: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  df=pd.DataFrame.from_csv(file_name)

In [3]:
df.head(10)

,post,topic,processed_post,sentiment
created_at,,,,
2018-07-05 10:39:40,"Hello Hacker-Newsers!<p>I’m Armin, co-maker of...",Twitter,hello hacker-news <p> ’ armin co-mak placid de...,postive
2018-07-05 05:34:26,I don&#x27;t follow. I have a Twitter profile....,Twitter,#x27 follow twitter profil someon els share ra...,postive
2018-07-03 01:29:50,There are two closely intertwined but separate...,Twitter,two close intertwin separ issu central govern ...,postive
2018-06-25 08:14:35,Thanks for sharing this. Fascinating!<p>I&#x27...,Twitter,thank share fascin <p> #x27 big fan serv conte...,postive
2018-05-27 10:26:52,"Go does not use the C stack, so calling into C...",Twitter,go use c stack call c requir set c stack tramp...,negative
2018-05-16 17:51:56,This might not be an area people want to discu...,Twitter,might area peopl want discuss price make grey ...,postive
2018-05-16 17:44:15,It seems like they&#x27;re waiting for enterpr...,Twitter,"seem like #x27 wait enterpris price <a href=""h...",neutral
2018-05-14 23:30:19,"There was a point in time, around 5 years ago ...",Twitter,point time around 5 year ago less third parti ...,postive
2018-05-09 02:59:56,"One time, a giant tech company staffed by geni...",Twitter,one time giant tech compani staf genius releas...,postive
2018-05-03 06:14:09,&gt; I&#x27;m aware of that–that&#x27;s why I ...,Twitter,gt #x27 awar – #x27 said possibl javascript #x...,postive

In [4]:
df1=pd.pivot_table(df,index=df.index.year,columns=df["topic"],values="post", aggfunc="count")

In [5]:
df1

topic       Facebook  Twitter
created_at
2007             NaN      2.0
2008             NaN      2.0
2009             NaN      5.0
2010             2.0      2.0
2011            26.0     26.0
2012            22.0     63.0
2013            60.0     20.0
2014            38.0     33.0
2015            48.0     41.0
2016            65.0     43.0
2017            47.0     39.0
2018            60.0     26.0

In [6]:
df2=df[df["sentiment"]=="postive"]

In [7]:
df2.head(10)

Empty DataFrame
Columns: [post, topic, processed_post, sentiment]
Index: []